-- MySQL Script generated by MySQL Workbench
-- Wed Apr 15 20:42:18 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema changing_lives
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema changing_lives
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `changing_lives` DEFAULT CHARACTER SET utf8 ;
USE `changing_lives` ;

-- -----------------------------------------------------
-- Table `changing_lives`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `changing_lives`.`users` (
  `user_id` INT(11) NOT NULL AUTO_INCREMENT,
  `real_name` CHAR(32) NOT NULL,
  `username` CHAR(32) NOT NULL,
  `password` CHAR(128) NOT NULL,
  `password_salt` CHAR(32) NOT NULL,
  `is_admin` BIT NOT NULL DEFAULT 0,
  `force_reset` BIT NOT NULL DEFAULT 1,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `changing_lives`.`logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `changing_lives`.`logs` (
  `logId` INT(11) NOT NULL AUTO_INCREMENT,
  `userId` INT(11) UNSIGNED NULL DEFAULT NULL,
  `dateTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `action` CHAR(32) NULL DEFAULT NULL,
  `entity` CHAR(32) NULL DEFAULT NULL,
  `newData` JSON NULL DEFAULT NULL,
  `oldData` JSON NULL DEFAULT NULL,
  PRIMARY KEY (`logId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `changing_lives`.`files`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `changing_lives`.`files` (
  `file_id` INT(11) NOT NULL AUTO_INCREMENT,
  `file_name` CHAR(32) NOT NULL,
  `file_link` TEXT NOT NULL,
  `section_id` INT(11) NOT NULL,
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`file_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `changing_lives`.`sections`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `changing_lives`.`sections` (
  `section_id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `article_text` TEXT NOT NULL,
  `section_name` CHAR(32) NOT NULL,
  `position` INT(11) NOT NULL,
  PRIMARY KEY (`section_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `changing_lives`.`child_comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `changing_lives`.`child_comments` (
  `child_id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `parent_id` INT(11) NOT NULL,
  `child_comment` TEXT NOT NULL,
  PRIMARY KEY (`child_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `changing_lives`.`parent_comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `changing_lives`.`parent_comments` (
  `parent_id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `parent_comment` TEXT NOT NULL,
  `parent_title` CHAR(32) NOT NULL,
  PRIMARY KEY (`parent_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
